<?php

return [
    'multisite' => false,

    'default_layout' => 'layouts.internal',

    'backend_side_bar_layout' => true,

    'pilot_color' => '#43379D',
    'pilot_color_dark' => '#322975',
    'pilot_color_light' => '#5B4EC1',
    'pilot_color_highlight' => '#786bd5',

    'social_image' => env('SOCIAL_IMAGE'),
    'social_image_width' => env('SOCIAL_IMAGE_WIDTH'),
    'social_image_height' => env('SOCIAL_IMAGE_HEIGHT'),

    'table_prefix' => env('PILOT_TABLE_PREFIX', 'pilot_'),

    'plugins' => [
        'pages' => [
            'name' => 'Pages',
            'enabled' => true,
            'url' => ['admin.page.index'],
            'routePattern' => 'admin.page.*',
            'view' => null,
            'vertical_image' => true,
            'target' => '_self',
            'children' => [
                'manage_pages' => [
                    'name' => 'Manage Pages',
                    'enabled' => true,
                    'url' => ['admin.page.index'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
                'add_page' => [
                    'name' => 'Add New Page',
                    'enabled' => true,
                    'url' => ['admin.page.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
                'manage_menus' => [
                    'name' => 'Manage Menus',
                    'enabled' => true,
                    'url' => ['admin.menu.index'],
                    'routePattern' => 'admin.menu.*',
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
            ],
        ],
        'news' => [
            'name' => 'News',
            'enabled' => true,
            'url' => ['admin.post.index'],
            'routePattern' => 'admin.post.*',
            'view' => null,
            'target' => '_self',
            'image_background_swatch_picker' => true,
            'background-color-options' => [
                '#43379D',
                '#322975',
                '#5B4EC1',
                '#786bd5'
            ],
            'children' => [
                'manage_post' => [
                    'name' => 'Manage News',
                    'enabled' => true,
                    'url' => ['admin.post.index'],
                    'routePattern' => null,
                    'view' => 'published',
                    'target' => '_self',
                    'children' => null,
                ],
                'add_post' => [
                    'name' => 'Add New Post',
                    'enabled' => true,
                    'url' => ['admin.post.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
            ]
        ],
        'events' => [
            'name' => 'Events',
            'enabled' => false,
            'url' => ['admin.event.index'],
            'routePattern' => 'admin.event.*',
            'view' => null,
            'target' => '_self',
            'children' => [
                'manage_event' => [
                    'name' => 'Manage Events',
                    'enabled' => true,
                    'url' => ['admin.event.index'],
                    'routePattern' => null,
                    'view' => 'published',
                    'target' => '_self',
                    'children' => null,
                ],
                'add_event' => [
                    'name' => 'Add New Event',
                    'enabled' => true,
                    'url' => ['admin.event.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
            ]
        ],
        'annoucements' => [
            'name' => 'Alerts',
            'enabled' => true,
            'url' => ['admin.annoucement.index'],
            'routePattern' => 'admin.annoucement.*',
            'view' => null,
            'target' => '_self',
            'children' => [
                'manage_alerts' => [
                    'name' => 'Manage Alerts',
                    'enabled' => true,
                    'url' => ['admin.annoucement.index'],
                    'routePattern' => null,
                    'view' => 'published',
                    'target' => '_self',
                    'children' => null,
                ],
                'add_alert' => [
                    'name' => 'Add New Alert',
                    'enabled' => true,
                    'url' => ['admin.annoucement.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
            ]
        ],
        'resources' => [
            'name' => 'Resources + Categories',
            'enabled' => false,
            'url' => ['admin.resource.index'],
            'routePattern' => 'admin.resource.*',
            'view' => 'published',
            'target' => '_self',
            'children' => [
                'manage_resource' => [
                    'name' => 'Manage Resources',
                    'enabled' => true,
                    'url' => ['admin.resource.index'],
                    'routePattern' => null,
                    'view' => 'published',
                    'target' => '_self',
                    'children' => null,
                ],
                'add_resource' => [
                    'name' => 'Add New Resource',
                    'enabled' => true,
                    'url' => ['admin.resource.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
                'resource_category' => [
                    'name' => 'Manage Resource Categories',
                    'enabled' => true,
                    'url' => ['admin.resourcecategory.index'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null
                ],
                'add_resource_category' => [
                    'name' => 'Add New Resource Category',
                    'enabled' => true,
                    'url' => ['admin.resourcecategory.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null
                ]
            ],
        ],
        'employees' => [
            'name' => 'Employees + Departments',
            'enabled' => false,
            'url' => ['admin.employee.index'],
            'routePattern' => 'admin.employee.*',
            'view' => 'published',
            'target' => '_self',
            'birth_date' => true,
            'cell_phone' => true,
            'extension' => true,
            'bio' => true,
            'children' => [
                'manage_employee' => [
                    'name' => 'Manage Employees',
                    'enabled' => true,
                    'url' => ['admin.employee.index'],
                    'routePattern' => null,
                    'view' => 'published',
                    'target' => '_self',
                    'children' => null,
                ],
                'add_employee' => [
                    'name' => 'Add New Employee',
                    'enabled' => true,
                    'url' => ['admin.employee.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
                'departments' => [
                    'name' => 'Manage Departments',
                    'enabled' => true,
                    'url' => ['admin.department.index'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                    'tags_relationship' => true,
                    'resources_relationship' => true,
                    'sort_employees_within_department' => false
                ],
                'add_departments' => [
                    'name' => 'Add New Department',
                    'enabled' => true,
                    'url' => ['admin.department.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                    'tags_relationship' => true,
                    'resources_relationship' => true,
                ]
            ],
        ],
        'testimonials' => [
            'name' => 'Testimonials',
            'enabled' => false,
            'url' => ['admin.testimonial.index'],
            'routePattern' => 'admin.testimonial.*',
            'view' => 'published',
            'target' => '_self',
            'international-testimonials' => false,
            'children' => [
                'manage_testimonial' => [
                    'name' => 'Manage Testimonials',
                    'enabled' => true,
                    'url' => ['admin.testimonial.index'],
                    'routePattern' => null,
                    'view' => 'published',
                    'target' => '_self',
                    'children' => null,
                ],
                'add_testimonial' => [
                    'name' => 'Add New Testimonial',
                    'enabled' => true,
                    'url' => ['admin.testimonial.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
            ]
        ],
        'faqs' => [
            'name' => 'FAQs + Categories',
            'enabled' => false,
            'url' => ['admin.faq.index'],
            'routePattern' => 'admin.faq.*',
            'view' => 'published',
            'target' => '_self',
            'uses-long-answers' => false,
            'children' => [
                'manage_employee' => [
                    'name' => 'Manage FAQs',
                    'enabled' => true,
                    'url' => ['admin.faq.index'],
                    'routePattern' => null,
                    'view' => 'published',
                    'target' => '_self',
                    'children' => null,
                ],
                'add_employee' => [
                    'name' => 'Add New FAQ',
                    'enabled' => true,
                    'url' => ['admin.faq.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
                'manage_faq_categories' => [
                    'name' => 'Manage FAQ Categories',
                    'enabled' => true,
                    'url' => ['admin.faqcategory.index'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null
                ],
                'add_faq_category' => [
                    'name' => 'Add New FAQ Category',
                    'enabled' => true,
                    'url' => ['admin.faqcategory.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
            ]
        ],
        'products' => [
            'name' => 'Products + Categories',
            'enabled' => true,
            'url' => ['admin.product.index'],
            'routePattern' => 'admin.product.*',
            'view' => 'published',
            'target' => '_self',
            'fields' => [
                'name' => true,
                'price' => true,
                'short_description' => true,
                'full_description' => true,
                'featured_image' => true,
                'gallery' => true,
                'categories' => true,
                'status' => true
            ],
            'children' => [
                'manage_products' => [
                    'name' => 'Manage Products',
                    'enabled' => true,
                    'url' => ['admin.product.index'],
                    'routePattern' => null,
                    'view' => 'published',
                    'target' => '_self',
                    'children' => null,
                ],
                'add_product' => [
                    'name' => 'Add New Product',
                    'enabled' => true,
                    'url' => ['admin.product.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
                'manage_product_categories' => [
                    'name' => 'Manage Product Categories',
                    'enabled' => true,
                    'url' => ['admin.productcategory.index'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'fields' => [
                        'title' => true,
                        'featured_image' => true,
                        'product_selector' => true,
                        'product_sort_method' => 'manual_sort' // options include: manual_sort, alpha_sort
                    ],
                    'children' => null
                ],
                'add_product_category' => [
                    'name' => 'Add New Product Category',
                    'enabled' => true,
                    'url' => ['admin.productcategory.create'],
                    'routePattern' => null,
                    'view' => null,
                    'target' => '_self',
                    'children' => null,
                ],
            ]
        ],
        'forms' => [
            'name' => 'Forms',
            'enabled' => false,
            'url' => ['admin.form.index'],
            'routePattern' => 'admin.form.*',
            'view' => null,
            'target' => '_self',
            'children' => null
        ],
        'styles' => [
            'name' => 'Styles',
            'enabled' => false,
            'url' => ['admin.style.index'],
            'routePattern' => 'admin.style.*',
            'view' => null,
            'target' => '_self',
            'children' => null
        ],
    ],

    'disable_page_parts' => true,

    'disable_menu_builder' => false,
];
